Added spotless format

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -1,7 +1,7 @@
 # This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
 # For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
 
-name: Maven Package (Snapshot)
+name: Maven Package (Nightly)
 
 on:
   workflow_dispatch:
@@ -9,7 +9,7 @@ on:
     - cron: '30 3 * * *'
 
 jobs:
-  build:
+  prepare:
     runs-on: self-hosted
     permissions:
       contents: read
@@ -28,13 +28,21 @@ jobs:
       id: changes
       if: github.event_name == 'schedule'
       run: |
-        git log --since='26 hours ago' -1 --oneline -- . ':(exclude).github/**'
-        if [ -n "$(git log --since='26 hours ago' -1 --oneline -- . ':(exclude).github/**')" ]; then
-          echo "has_changes=true" >> $GITHUB_OUTPUT
-        else
-          echo "has_changes=false" >> $GITHUB_OUTPUT
-        fi
-        cat $GITHUB_OUTPUT
+        if git log \
+            --since='26 hours ago' \
+            -1 \
+            --oneline \
+            --invert-grep \
+            --grep='^\[NIGHTLY\]' \
+            --author='github-actions' \
+            --author='.*\[bot\]' \
+            --all-match \
+            -- . ':(exclude).github/**' | grep -q .; then
+
+            echo "has_changes=true" >> $GITHUB_OUTPUT
+          else
+            echo "has_changes=false" >> $GITHUB_OUTPUT
+          fi
         
     - name: Detect SNAPSHOT version
       id: snapshot
@@ -46,17 +54,60 @@ jobs:
         else
           echo "is_snapshot=false" >> $GITHUB_OUTPUT
         fi
-        
-    - name: Stop if not snapshot
-      if: steps.snapshot.outputs.is_snapshot == 'false'
+
+    - name: Decide if pipeline should run
+      id: decision
       run: |
-        echo "Not a snapshot. Skipping build."
-        
-    - name: Stop if no changes
-      if: github.event_name == 'schedule' && steps.changes.outputs.has_changes == 'false'
-      run: |
-        echo "No commits in last 26 hours. Skipping build."
-        
+        if [[ "${{ steps.snapshot.outputs.is_snapshot }}" == "true" && "${{ steps.changes.outputs.has_changes }}" == "true" ]]; then
+          echo "should_run=true" >> $GITHUB_OUTPUT
+        else
+          echo "should_run=false" >> $GITHUB_OUTPUT
+        fi
+
+  format:
+    runs-on: self-hosted
+    needs: prepare
+    if: needs.prepare.outputs.should_run == 'true'
+
+    permissions:
+      contents: write
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-java@v5
+        with:
+          distribution: temurin
+          java-version: 17
+
+      - name: Apply formatting
+        run: mvn -B spotless:apply
+
+      - name: Commit & push if needed
+        run: |
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+
+          git add .
+          git diff --cached --quiet || git commit -m "[NIGHTLY] Apply code formatting"
+
+          git push || echo "Push failed, continuing..."
+
+  build:
+    runs-on: self-hosted
+    needs: format
+    if: needs.prepare.outputs.should_run == 'true'
+
+    permissions:
+      contents: write
+
+    env:
+      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
+      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
+
+    steps:
     - uses: actions/setup-java@v5
       if: >
         steps.snapshot.outputs.is_snapshot == 'true' &&
